

*** 
``` {r}
setwd("~/projects/Classes/FoundationsOfDataScience_sliderule/github/part5_analytics/15.071x_The_Analytics_Edge/Unit04_Trees")

```

## Unit 4

Classification and regression trees (CART)

***

### State data revisited


``` {r}
data(state)
statedata = data.frame(state.x77)

str(statedata)

# 1.1
lifeExp = lm(Life.Exp ~ Population + Income + Illiteracy + Murder + HS.Grad + Frost + Area, data = statedata)
summary(lifeExp)

# 1.2
SSE = sum(lifeExp$residuals ^ 2)
SSE
# sum((statedata$Life.Exp - Predictions)^2)

# 1.3
# remove over previous linear model Income + Illiteracy + Area
lifeExp2 = lm(Life.Exp ~ Population + Murder + HS.Grad + Frost, data = statedata)
summary(lifeExp2)

# 1.4
SSE = sum(lifeExp2$residuals ^ 2)
SSE

# 2.1
# Load CART packages
library(rpart)
library(rpart.plot)

# CART model
predCart = rpart(Life.Exp ~ Population + Income + Illiteracy + Murder + HS.Grad + Frost + Area, data=statedata)
prp(predCart)

# 2.2
predCartValues = predict(predCart)
summary(predCartValues)
str(predCartValues)
sum((predCartValues - statedata$Life.Exp)^2)

# 2.3
predCart2 = rpart(Life.Exp ~ Population + Income + Illiteracy + Murder + HS.Grad + Frost + Area, data=statedata, minbucket = 5)
prp(predCart2)

# 2.4
# 2.5 
predCart2Values = predict(predCart2)
sum((predCart2Values - statedata$Life.Exp)^2)


# 2.6
predCart3 = rpart(Life.Exp ~ Area, data=statedata, minbucket = 1)
predCart3Values = predict(predCart3)
sum((predCart3Values - statedata$Life.Exp)^2)

prp(predCart3)

# 3.1
library(caret)
set.seed(111)

# Number of folds
tr.control = trainControl(method = "cv", number = 10)

# cp values
cp.grid = expand.grid( .cp = seq(0.01, 0.50, 0.01))

tr = train(Life.Exp ~ ., data = statedata, method = "rpart", trControl = tr.control, tuneGrid = cp.grid)
tr

# 3.2
best.tree = tr$finalModel
prp(best.tree)
predCart4 = rpart(Life.Exp ~ ., data = statedata, cp = 0.12)
prp(predCart4)

# 3.3
predCart4Values = predict(predCart4)
sum((predCart4Values - statedata$Life.Exp)^2)

# 3.5
set.seed(111)

# Number of folds
tr.control = trainControl(method = "cv", number = 10)

# cp values
cp.grid = expand.grid( .cp = seq(0.01, 0.50, 0.01))

tr2 = train(Life.Exp ~ Area, data = statedata, method = "rpart", trControl = tr.control, tuneGrid = cp.grid)
tr2
# cp = 0.03

predCart5 = rpart(Life.Exp ~ Area, data = statedata, cp = 0.03)
prp(predCart5)

# 3.7
predCart5Values = predict(predCart5)
sum((predCart5Values - statedata$Life.Exp)^2)

```
