

*** 
``` {r}
setwd("~/projects/Classes/FoundationsOfDataScience_sliderule/github/part5_analytics/15.071x_The_Analytics_Edge")

```

## Unit 1

***
``` {r}
sd(c(5,8,12))
which.min(c(4,1,6))
```

### working with data: An introduction to R

#### Loading data files

``` {r}
WHO = read.csv("WHO.csv")
str(WHO)
summary(WHO)

WHO_Europe = subset(WHO, Region == "Europe")
str(WHO_Europe)

write.csv(WHO_Europe, "WHO_Europe.csv")
rm(WHO_Europe)
ls()

```


#### data analysis - summary stats and scatterplots

``` {r}
WHO$Under15
mean(WHO$Under15)
sd(WHO$Under15)
summary(WHO$Under15)

which.min(WHO$Under15)
WHO$Country[86]

which.max(WHO$Under15)
WHO$Country[124]

library(psych)
describe(WHO)
```

``` {r}
plot(WHO$GNI, WHO$FertilityRate)
Outliers = subset(WHO, GNI > 10000 & FertilityRate > 2.5)
nrow(Outliers)

Outliers[c("Country", "GNI", "FertilityRate")]


```


``` {r}
hist(WHO$CellularSubscribers)
boxplot(WHO$LifeExpectancy ~ WHO$Region)
boxplot(WHO$LifeExpectancy ~ WHO$Region, xlab = "", ylab = "Life Expectancy", main = "Life Expectancy of Countries by Region")

tapply(WHO$Over60, WHO$Region, mean)

tapply(WHO$LiteracyRate, WHO$Region, min)

tapply(WHO$LiteracyRate, WHO$Region, min, na.rm = TRUE)
```


``` {r}


```

##### questions


``` {r}
mean(WHO$Over60)

which.min(WHO$Over60)
WHO$Country[183]

which.max(WHO$LiteracyRate)
WHO$Country[44]


tapply(WHO$ChildMortality, WHO$Region, min, na.rm = TRUE)
```

## Assignment 1

``` {r}
poll <- read.csv("AnonymityPoll.csv")

# 1.1
summary(poll)
str(poll)

# 1.2
table(poll$Smartphone)
summary(poll$Smartphone)

# 1.3
table(poll$Sex, poll$Region)

table(poll$State, poll$Region)


# 2.1
table(poll$Internet.Use, poll$Smartphone)

# 2.2
summary(poll$Internet.Use)
summary(poll$Smartphone)

# 2.3
limited <- subset(poll, poll$Internet.Use | poll$Smartphone)
str(limited)

# 3.1
summary(limited)

# 3.2
mean(limited$Info.On.Internet)

# 3.3
zeroOnInternet <- subset(limited, limited$Info.On.Internet == 0)
str(zeroOnInternet)

elevenOnInternet <- subset(limited, limited$Info.On.Internet == 11)
str(elevenOnInternet)

# 3.4
yesWorryAboutInfo <- subset(limited, limited$Worry.About.Info == 1)
table(limited$Worry.About.Info)
386 / (404 + 386)
summary(limited$Worry.About.Info)

# 3.5
summary(limited$Anonymity.Possible)

# 3.6
summary(limited$Tried.Masking.Identity)

# 3.7
summary(limited$Privacy.Laws.Effective)

# 4.1
hist(limited$Age)

# 4.2 
#plot(limited$Age, limited$Info.On.Internet)
table(limited$Age, limited$Info.On.Internet)
#summary(table(limited$Age, limited$Info.On.Internet))
infoOnInternetBYage <- data.frame(table(limited$Age,limited$Info.On.Internet))
summary(infoOnInternetBYage)
max(infoOnInternetBYage$Freq)

# 4.3
jitter(c(1, 2, 3))
jitter(c(1, 2, 3))
jitter(c(1, 2, 3))

# 4.4
plot(limited$Age, limited$Info.On.Internet)
plot(jitter(limited$Age), jitter(limited$Info.On.Internet))
# ->  Older age seems moderately associated with a smaller value for Info.On.Internet 

# 4.5
###tapply(USDA$Iron, USDA$HighProtein, mean, na.rm=TRUE)
#tapply(limited$Smartphone, limited$Internet.Use, mean, na.rm = TRUE)
#tapply(limited$Smartphone, limited$Info.On.Internet, mean, na.rm = TRUE)
tapply(limited$Info.On.Internet, limited$Smartphone, mean, na.rm = TRUE)

# 4.6


```
