---
title: "iris - start with dplyr"
output: html_document
---


### Loading dplyr and iris dataset

http://archive.ics.uci.edu/ml/datasets/Iris


```{r}
library(ggplot2)
# load packages
suppressMessages(library(dplyr))
#install.packages('rJava', type='source')
#install.packages('rJava')
library('rJava')

# explore data
data("iris")
head(iris)
```

***


#### some dplyr summaries and observations


``` {r}

glimpse(iris)

iris %>%
        group_by(Species) %>%
        summarise(avg = mean(Sepal.Width)) %>%
        arrange(avg)

summarise(iris, avg = mean(Sepal.Length))
summarise_each(iris, funs(mean))

summarise_each(select(iris, -Species), funs(mean))
```

#### some new variables

``` {r}
iris <- mutate(iris, sepal = Sepal.Length + Sepal.Width)
iris <- mutate(iris, sepal2 = Sepal.Length - Sepal.Width)

```

### scatterplot matrices

``` {r}
library(GGally)
theme_set(theme_minimal(20))


# seed
set.seed(1828)
names(iris)
#ggpairs(iris[sample.int(nrow(iris), 60), ])
ggpairs(iris)

```



### some linear models


``` {r from matplot}

# reload iris data
data("iris")

require(grDevices)
matplot((-4:5)^2, main = "Quadratic") # almost identical to plot(*)
sines <- outer(1:20, 1:4, function(x, y) sin(x / 20 * pi * y))
matplot(sines, pch = 1:4, type = "o", col = rainbow(ncol(sines)))
matplot(sines, type = "b", pch = 21:23, col = 2:5, bg = 2:5,
        main = "matplot(...., pch = 21:23, bg = 2:5)")

x <- 0:50/50
matplot(x, outer(x, 1:8, function(x, k) sin(k*pi * x)),
        ylim = c(-2,2), type = "plobcsSh",
        main= "matplot(,type = \"plobcsSh\" )")
## pch & type =  vector of 1-chars :
matplot(x, outer(x, 1:4, function(x, k) sin(k*pi * x)),
        pch = letters[1:4], type = c("b","p","o"))

lends <- c("round","butt","square")
matplot(matrix(1:12, 4), type="c", lty=1, lwd=10, lend=lends)
text(cbind(2.5, 2*c(1,3,5)-.4), lends, col= 1:3, cex = 1.5)

table(iris$Species) # is data.frame with 'Species' factor
iS <- iris$Species == "setosa"
iV <- iris$Species == "versicolor"
op <- par(bg = "bisque")
matplot(c(1, 8), c(0, 4.5), type =  "n", xlab = "Length", ylab = "Width",
        main = "Petal and Sepal Dimensions in Iris Blossoms")
matpoints(iris[iS,c(1,3)], iris[iS,c(2,4)], pch = "sS", col = c(2,4))
matpoints(iris[iV,c(1,3)], iris[iV,c(2,4)], pch = "vV", col = c(2,4))
legend(1, 4, c("    Setosa Petals", "    Setosa Sepals",
               "Versicolor Petals", "Versicolor Sepals"),
       pch = "sSvV", col = rep(c(2,4), 2))

nam.var <- colnames(iris)[-5]
nam.spec <- as.character(iris[1+50*0:2, "Species"])
iris.S <- array(NA, dim = c(50,4,3),
                dimnames = list(NULL, nam.var, nam.spec))
for(i in 1:3) iris.S[,,i] <- data.matrix(iris[1:50+50*(i-1), -5])

matplot(iris.S[, "Petal.Length",], iris.S[, "Petal.Width",], pch = "SCV",
        col = rainbow(3, start = 0.8, end = 0.1),
        sub = paste(c("S", "C", "V"), dimnames(iris.S)[[3]],
                    sep = "=", collapse= ",  "),
        main = "Fisher's Iris Data")
par(op)
```

***

### add a derived variable

``` {r}

iris$Species_id <- with(iris, ifelse(Species == 'setosa', 1, 
                  ifelse(Species == 'versicolor', 2, 
                         ifelse(Species == 'virginica', 3, NA))))

```


``` {r}
#install.packages("FSelector")
library(FSelector)

subset <- cfs(Species~., iris)
f <- as.simple.formula(subset, "Species")
print(f)
```

http://stackoverflow.com/questions/18589018/reduce-dataset-with-fselector-in-r

``` {r}
data(iris)
weights <- relief(Species~., iris, neighbours.count = 5, sample.size = 20)
subset <- cutoff.k(weights, 2)
f <- as.simple.formula(subset, "Species")

newdata <-  iris[,cutoff.k(weights, 2)] 
```